### ISSUE TITLE
Comment after anchor attach

### ISSUE THREAD

**Issue by fisker** [ikatyang/yaml-unist-parser#277]
```yaml
key: &anchor
  # comment
  - value
```

comment is attached as `sequence.middleComments`, maybe better `sequenceItem.leadingComments`?

**Comment by ikatyang** [comment]
The current rule of attaching leading/middle comments is to attach them to the _largest_ node next to it, for example the following comment is attached to `mapping` instead of `mappingItem`/`mappingKey`/`plain`, breaking the consistency does not seem to be a good idea IMO.

```yml
# comment
key: value
```

And the linked issue seems to be unrelated to this issue, where the ignore comment already worked with `sequence.leadingComments`, it just did not recognize the `sequence.middleComments` case.

**Comment by fisker** [comment]
In that Prettier issue, it seems user mean to ignore that `sequenceItem`, and `prettier-ignore` normally in `leadingComments`, should this special case handle in Prettier or here?

Does `sequence.middleComments` only appear before the first child?

**Comment by ikatyang** [comment]
> In that Prettier issue, it seems user mean to ignore that `sequenceItem`, ...

There is only one sequence item in the sequence so I'm not sure if they meant `sequence` or `sequenceItem` given that both of them have the exact same range. And changing the comment attaching  from `sequence` to `sequenceItem` would be a breaking change for Prettier since the `prettier-ignore` range would be wider.

> ...and `prettier-ignore` normally in `leadingComments`, should this special case handle in Prettier or here?

Since the ignore comment is a Prettier-specific feature, I'd say it should be handled on the Prettier side.

> Does `sequence.middleComments` only appear before the first child?

Since the tag/anchor can only appear in front of the node, Yes.

https://github.com/ikatyang/yaml-unist-parser/blob/92ea25423fc23bc160477d21cc51d7beeace2a14/src/types.ts#L35-L36

https://github.com/ikatyang/yaml-unist-parser/blob/92ea25423fc23bc160477d21cc51d7beeace2a14/src/types.ts#L44-L45

https://github.com/ikatyang/yaml-unist-parser/blob/92ea25423fc23bc160477d21cc51d7beeace2a14/src/types.ts#L49-L50

https://github.com/ikatyang/yaml-unist-parser/blob/92ea25423fc23bc160477d21cc51d7beeace2a14/src/types.ts#L54-L55

**Comment by fisker** [comment]
Thank you! I'll try to fix that issue.
